### PR TITLE
Bump version to 0.7.0

### PR DESCRIPTION
**Pull request by dosas**
It would be nice to have a new release

should be merged after https://github.com/theforeman/ldap_fluff/pull/81

### CODE REVIEW

**Comment by dosas** [comment]
@ezr-ondrej Are you fine with a new release?

**Review by ezr-ondrej — APPROVED** [review]
I'm but we will also should also plan to do releasing and packaging for it.
I'm happy to tag the new version, but I don't think I should (just because I'm not very active and I might not be around to fix it if it breaks ;) ) 
@evgeni would you do it?

**Comment by dosas** [comment]
> I'm but we will also should also plan to do releasing and packaging for it. I'm happy to tag the new version, but I don't think I should (just because I'm not very active and I might not be around to fix it if it breaks ;) ) @evgeni would you do it?

AFAIK: 
* Releasing is now (due to the release workflow) just pushing/creating a tag.
* The new gem versions are automatically picked up by foreman-packaging

**Comment by evgeni** [comment]
Correct, release is just a tag now, and packaging is automatically updated once a week, so no "manual" work is needed.

What I do not know is how quickly we'd see problem reports (if any, e.g. the Foreman nightly pipelines don't test LDAP), but I guess that shouldn't block us from releasing.

**Comment by ezr-ondrej** [comment]
Lets push some buttons, then :)
Should I push 'em?

**Comment by ezr-ondrej** [comment]
Thank you @dosas ! :orange_heart:

**Pull request merged**
